version: '3.8'
services: 
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
    - type: bind
      source: ./school.sql
      target: /schemes/school.sql
